"""Base strategy class."""

from abc import ABC, abstractmethod
from typing import Any, Optional
from src.models.market import MarketSnapshot
from src.models.alert import Alert
from src.services.notifier import get_notifier
from src.utils.logger import get_logger

logger = get_logger(__name__)


class BaseStrategy(ABC):
    """Base class for all trading strategies."""

    def __init__(self, name: str) -> None:
        """Initialize strategy.

        Args:
            name: Strategy name for identification
        """
        self.name = name
        self._notifier = get_notifier()
        self._alerts: list[Alert] = []

    @abstractmethod
    def analyze(
        self,
        market_id: str,
        question: str,
        snapshots: list[MarketSnapshot],
    ) -> list[Alert]:
        """Analyze market data and generate alerts.

        Args:
            market_id: Market identifier
            question: Market question
            snapshots: Historical price snapshots

        Returns:
            List of generated alerts
        """
        pass

    def get_alerts(self) -> list[Alert]:
        """Get alerts generated by this strategy."""
        return self._alerts

    def clear_alerts(self) -> None:
        """Clear stored alerts."""
        self._alerts = []

    def log_analysis(self, market_id: str, result: str) -> None:
        """Log analysis results."""
        logger.info(
            f"[{self.name}] {result}",
            extra={"strategy": self.name, "market_id": market_id},
        )
